# Singular value decomposition

## Equations

\begin{equation}
\mathbf{A} = \mathbf{P} \mathbf{D} \mathbf{P}^{-1}
\end{equation}

\begin{equation}
\mathbf{AP} = \mathbf{PD}
\end{equation}

\begin{equation}
\mathbf{Ap}_i = \mathbf{Pd}_i = d_{ii}\mathbf{p}_i
\end{equation}

\begin{equation}
\mathbf{Ax} = \lambda \mathbf{x}
\end{equation}

\begin{equation}
\mathbf{A}_{m \times n} = \mathbf{U}_{m \times m}\mathbf{\Sigma}_{m \times n} (\mathbf{V}_{n \times n})^T
\end{equation}

## Example

In [1]:
import numpy as np
from numpy import linalg

In [2]:
dim = (2, 3)
A = np.random.randint(100, size=dim)
print(A)

[[50 90 75]
 [30 67 15]]


In [3]:
U, S, V_T = linalg.svd(A)
print("-------")
print(U)
print("-------")
print(S)
print("-------")
print(V_T)

-------
[[-0.87253108 -0.48855862]
 [-0.48855862  0.87253108]]
-------
[145.15928101  27.70889997]
-------
[[-0.40151282 -0.76647682 -0.50129905]
 [ 0.06308448  0.52291166 -0.85004926]
 [-0.91367817  0.37292987  0.16160294]]


In [4]:
S_0 = np.zeros((2, 3), float)
np.fill_diagonal(S_0, S)
print(S_0)

[[145.15928101   0.           0.        ]
 [  0.          27.70889997   0.        ]]


In [5]:
A_0 = U.dot(S_0.dot(V_T))
print(A_0)

[[50. 90. 75.]
 [30. 67. 15.]]


In [6]:
I = U.dot(U.T)
print(I)

[[ 1.00000000e+00 -6.75401833e-17]
 [-6.75401833e-17  1.00000000e+00]]


In [7]:
I = V_T.dot(V_T.T)
print(I)

[[ 1.00000000e+00  9.07618417e-17  1.52580410e-16]
 [ 9.07618417e-17  1.00000000e+00 -4.81707472e-17]
 [ 1.52580410e-16 -4.81707472e-17  1.00000000e+00]]


## Application
### Matrix approximation

In [8]:
S_1 = np.zeros(dim, float)
S_1[0][0] = S[0]
print(S_1)

[[145.15928101   0.           0.        ]
 [  0.           0.           0.        ]]


In [9]:
A_1 = U.dot(S_1.dot(V_T))
print(A_1)

[[50.85400121 97.07887564 63.49252457]
 [28.47481434 54.35762959 35.5515359 ]]


In [10]:
S_2 = np.zeros(dim, float)
S_2[1][1] = S[1]
print(S_1)

[[145.15928101   0.           0.        ]
 [  0.           0.           0.        ]]


In [11]:
A_2 = U.dot(S_2.dot(V_T))
print(A_2)

[[ -0.85400121  -7.07887564  11.50747543]
 [  1.52518566  12.64237041 -20.5515359 ]]


In [12]:
A_3 = A_1 + A_2

print(A_0)
print("-------")
print(A_1)
print("-------")
print(A_2)
print("-------")
print(S)
print("-------")
print(A_3)

[[50. 90. 75.]
 [30. 67. 15.]]
-------
[[50.85400121 97.07887564 63.49252457]
 [28.47481434 54.35762959 35.5515359 ]]
-------
[[ -0.85400121  -7.07887564  11.50747543]
 [  1.52518566  12.64237041 -20.5515359 ]]
-------
[145.15928101  27.70889997]
-------
[[50. 90. 75.]
 [30. 67. 15.]]
