# Singular value decomposition

## Equations

\begin{equation}
\mathbf{A} = \mathbf{P} \mathbf{D} \mathbf{P}^{-1}
\end{equation}

\begin{equation}
\mathbf{AP} = \mathbf{PD}
\end{equation}

\begin{equation}
\mathbf{Ap}_i = \mathbf{Pd}_i = d_{ii}\mathbf{p}_i
\end{equation}

\begin{equation}
\mathbf{Ax} = \lambda \mathbf{x}
\end{equation}

\begin{equation}
\mathbf{A}_{m \times n} = \mathbf{U}_{m \times m}\mathbf{\Sigma}_{m \times n} (\mathbf{V}_{n \times n})^T
\end{equation}

## SVD Example

In [1]:
import numpy as np
from numpy import linalg

In [2]:
dim = (2, 3)
A = np.random.randint(100, size=dim)
print(A)

[[59 58 63]
 [69 82 40]]


In [3]:
U, S, V_T = linalg.svd(A)
print("-------")
print(U)
print("-------")
print(S)
print("-------")
print(V_T)

-------
[[-0.67097944 -0.74147595]
 [-0.74147595  0.67097944]]
-------
[152.81745155  23.36293008]
-------
[[-0.59384335 -0.65252911 -0.47069718]
 [ 0.10916868  0.51426379 -0.8506556 ]
 [-0.79714006  0.55654157  0.23415639]]


In [4]:
S_0 = np.zeros((2, 3), float)
np.fill_diagonal(S_0, S)
print(S_0)

[[152.81745155   0.           0.        ]
 [  0.          23.36293008   0.        ]]


In [5]:
A_0 = U.dot(S_0.dot(V_T))
print(A_0)

[[59. 58. 63.]
 [69. 82. 40.]]


In [6]:
I = U.dot(U.T)
print(I)

[[1.00000000e+00 1.07060675e-16]
 [1.07060675e-16 1.00000000e+00]]


In [7]:
I = V_T.dot(V_T.T)
print(I)

[[ 1.00000000e+00 -7.70632911e-17 -3.31600667e-17]
 [-7.70632911e-17  1.00000000e+00  3.79040277e-17]
 [-3.31600667e-17  3.79040277e-17  1.00000000e+00]]


## Application
### Matrix approximation

In [8]:
S_1 = np.zeros(dim, float)
S_1[0][0] = S[0]
print(S_1)

[[152.81745155   0.           0.        ]
 [  0.           0.           0.        ]]


In [9]:
A_1 = U.dot(S_1.dot(V_T))
print(A_1)

[[60.89113463 66.90861779 48.26404976]
 [67.28866675 73.93837728 53.33491616]]


In [10]:
S_2 = np.zeros(dim, float)
S_2[1][1] = S[1]
print(S_2)

[[ 0.          0.          0.        ]
 [ 0.         23.36293008  0.        ]]


In [11]:
A_2 = U.dot(S_2.dot(V_T))
print(A_2)

[[ -1.89113463  -8.90861779  14.73595024]
 [  1.71133325   8.06162272 -13.33491616]]


In [12]:
A_3 = A_1 + A_2

print(A_0)
print("-------")
print(A_1)
print("-------")
print(A_2)
print("-------")
print(S)
print("-------")
print(A_3)

[[59. 58. 63.]
 [69. 82. 40.]]
-------
[[60.89113463 66.90861779 48.26404976]
 [67.28866675 73.93837728 53.33491616]]
-------
[[ -1.89113463  -8.90861779  14.73595024]
 [  1.71133325   8.06162272 -13.33491616]]
-------
[152.81745155  23.36293008]
-------
[[59. 58. 63.]
 [69. 82. 40.]]
